<?php
/*
 * Plugin Name: Star Citizen Localization
 * Plugin URI: https://github.com/ulrichdahl/WP-StarStrings
 * Description: Star Citizen Localization Tool for WordPress.
 * Version: 1.4.7
 * Author: Ulrich Dahl <ulrich.dahl@gmail.com>
 * Author URI: https://github.com/ulrichdahl/
 * License: GPL3
 * Tool: Opencode, LM Studio, google/gemma-4-26b-a4b
 * Text Domain: leaderboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'SC_LOC_PATH', plugin_dir_path( __FILE__ ) );
define( 'SC_LOC_URL', plugin_dir_url( __FILE__ ) );
define( 'SC_LOC_UPLOAD_DIR', wp_upload_dir()['basedir'] . '/sc-localization' );
define( 'SC_LOC_MESSAGE', '(Generated by United Danes Initiative)' );

// Load text domain for translations
add_action( 'init', 'sc_loc_load_textdomain' );

function sc_loc_load_textdomain() {
	load_plugin_textdomain( 'sc-localization', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}

// Register activation hook to create upload directory
register_activation_hook( __FILE__, 'sc_loc_activate' );
function sc_loc_activate() {
	if ( ! file_exists( SC_LOC_UPLOAD_DIR ) ) {
		wp_mkdir_p( SC_LOC_UPLOAD_DIR );
	}
}

add_action( 'init', 'set_locale_from_translatepress' );
function set_locale_from_translatepress() {
	// Tjek om TranslatePress er aktivt
	if ( function_exists( 'trp_get_locale' ) ) {
		$current_lang = trp_get_locale(); // Returnerer f.eks. 'da_DK', 'de_DE', 'fr_FR'
		// echo PHP_EOL.'<!-- '.__FILE__.':'.__LINE__.': '.$current_lang.'-->';

		if ( $current_lang ) {
			$current_lang = setlocale( LC_ALL, $current_lang );
		}
		// echo PHP_EOL.'<!-- '.__FILE__.':'.__LINE__.': '.$current_lang.' -->';
		// echo PHP_EOL.'<!-- '.__FILE__.':'.__LINE__.': '.setlocale(LC_ALL, null).' -->';
	}
}

function sc_format_date_with_tp($format = "EEEE d. MMMM HH:mm", $timestamp = null) {
	// Hent TranslatePress sprog eller fald tilbage til WP standard
	$lang = function_exists( 'trp_get_locale' ) ? trp_get_locale() : get_locale();

	// Opret formatter (Locale, Dato-størrelse, Tids-størrelse, Tidszone, Kalender, Mønster)
	$formatter = new IntlDateFormatter(
		$lang,
		IntlDateFormatter::FULL,
		IntlDateFormatter::SHORT,
		date_default_timezone_get(),
		IntlDateFormatter::GREGORIAN,
		$format
	);

	return $formatter->format( $timestamp ?? time());
}

require_once SC_LOC_PATH . 'admin/admin-menu.php';
require_once SC_LOC_PATH . 'includes/file-handler.php';
require_once SC_LOC_PATH . 'frontend/shortcode.php';
