<?php

/*
Plugin Name: Star Citizen Localization
Plugin URI: https://github.com/ulrich/sc-localization
Description: Star Citizen Localization Tool for WordPress.
Version: 1.4.0
Author: ulrich
License: GPL2
*/

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'SC_LOC_PATH', plugin_dir_path( __FILE__ ) );
define( 'SC_LOC_URL', plugin_dir_url( __FILE__ ) );
define( 'SC_LOC_UPLOAD_DIR', wp_upload_dir()['basedir'] . '/sc-localization' );
define( 'SC_LOC_MESSAGE', '(Generated by United Danes Initiative)' );

// Register filter as early as possible (at file load) to catch any locale calls
add_filter( 'plugin_locale', 'sc_loc_browser_locale_filter', 1, 2 );

// Load text domain for translations
add_action( 'init', 'sc_loc_load_textdomain' );
function sc_loc_load_textdomain() {
	$domain = 'sc-localization';
	$locale = apply_filters( 'plugin_locale', get_locale(), $domain );
	$mofile = $domain . '-' . $locale . '.mo';
	$path   = SC_LOC_PATH . 'languages/' . $mofile;

	if ( file_exists( $path ) ) {
		load_textdomain( $domain, $path );
	} else {
		// Fallback to load_plugin_textdomain which looks in standard locations
		load_plugin_textdomain( $domain, false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
	}
}

/**
 * Automatically detect browser language and switch locale for this plugin's domain if needed.
 */
function sc_loc_browser_locale_filter( $locale, $domain ) {
	if ( 'sc-localization' !== $domain ) {
		return $locale;
	}

	if ( ! empty( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) ) {
		$browser_langs     = explode( ',', $_SERVER['HTTP_ACCEPT_LANGUAGE'] );
		$available_locales = array(
			'da' => 'da_DK',
			'en' => 'en_US',
			'de' => 'de_DE',
			'fr' => 'fr_FR'
		);

		foreach ( $browser_langs as $lang_range ) {
			$lang       = strtolower( trim( explode( ';', $lang_range )[0] ) );
			$short_lang = substr( $lang, 0, 2 );

			if ( isset( $available_locales[ $short_lang ] ) ) {
				return $available_locales[ $short_lang ];
			}
		}
	}

	return $locale;
}

// Register activation hook to create upload directory
register_activation_hook( __FILE__, 'sc_loc_activate' );
function sc_loc_activate() {
	if ( ! file_exists( SC_LOC_UPLOAD_DIR ) ) {
		wp_mkdir_p( SC_LOC_UPLOAD_DIR );
	}
}

require_once SC_LOC_PATH . 'admin/admin-menu.php';
require_once SC_LOC_PATH . 'includes/file-handler.php';
require_once SC_LOC_PATH . 'frontend/shortcode.php';